// <auto-generated />
namespace Varta_Exercises.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Aloitus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aloitus));
        
        string IMigrationMetadata.Id
        {
            get { return "201809111626156_Aloitus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
